name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello world"
      - name: print goodbye!
        run: echo "Done bye!"
      - name: multiline shell cmd
        run: |
          echo "Starting script..."
          echo "Hello from GitHub Actions!" > output/logs/hello.txt
      
