name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello world"
      - name: print goodbye!
        run: echo "Done bye!"
      - name: multiline shell cmd
        run: |
          echo "Starting script..."
          echo "Hello from GitHub Actions!"
  build-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Build project
        run: |
          mkdir output
          echo "Hello, World!" > output/hello.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/
  
      
